spring:
  application:
    name: 26-Api-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: api-1
            uri: lb://03-MS-MICROSERVICE-01
            predicates: 
              - Path=/ms1/**,
          - id: api-2
            uri: lb://04-MS-MICROSERVICE-02
            predicates:
              - Path=/ms2/**
server:
  port: 3333
